// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OMS_API.Data;

namespace OMS_API.Migrations
{
    [DbContext(typeof(OMSContext))]
    [Migration("20201222120845_users")]
    partial class users
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("OMS_API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OMS_API.Models.Pais", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZonaId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ZonaId");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("OMS_API.Models.Recomendacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Informacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Validade")
                        .HasColumnType("bigint");

                    b.Property<string>("ZonaId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ZonaId");

                    b.ToTable("Recomendacoes");
                });

            modelBuilder.Entity("OMS_API.Models.Surto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DataDetecao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<long>("VirusId")
                        .HasColumnType("bigint");

                    b.Property<string>("ZonaId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("VirusId");

                    b.HasIndex("ZonaId");

                    b.ToTable("Surtos");
                });

            modelBuilder.Entity("OMS_API.Models.Virus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Virus");
                });

            modelBuilder.Entity("OMS_API.Models.Zona", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zonas");
                });

            modelBuilder.Entity("OMS_API.Models.Pais", b =>
                {
                    b.HasOne("OMS_API.Models.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaId");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("OMS_API.Models.Recomendacao", b =>
                {
                    b.HasOne("OMS_API.Models.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaId");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("OMS_API.Models.Surto", b =>
                {
                    b.HasOne("OMS_API.Models.Virus", "Virus")
                        .WithMany()
                        .HasForeignKey("VirusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OMS_API.Models.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaId");

                    b.Navigation("Virus");

                    b.Navigation("Zona");
                });
#pragma warning restore 612, 618
        }
    }
}
