// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafetyTourism.Data;

namespace SafetyTourism.Migrations
{
    [DbContext(typeof(SafetyContext))]
    [Migration("20201214200425_Afectado")]
    partial class Afectado
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("SafetyTourism.Models.AfectadoPor", b =>
                {
                    b.Property<int>("AfectadoPorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinoId")
                        .HasColumnType("int");

                    b.Property<int>("DoencaId")
                        .HasColumnType("int");

                    b.Property<string>("Gravidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InfectadosPor100k")
                        .HasColumnType("int");

                    b.HasKey("AfectadoPorId");

                    b.HasIndex("DestinoId");

                    b.HasIndex("DoencaId");

                    b.ToTable("AfectadoPor");
                });

            modelBuilder.Entity("SafetyTourism.Models.Destino", b =>
                {
                    b.Property<int>("DestinoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinoId");

                    b.ToTable("Destino");
                });

            modelBuilder.Entity("SafetyTourism.Models.Doenca", b =>
                {
                    b.Property<int>("DoencaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecomendacaoId")
                        .HasColumnType("int");

                    b.HasKey("DoencaId");

                    b.HasIndex("RecomendacaoId");

                    b.ToTable("Doenca");
                });

            modelBuilder.Entity("SafetyTourism.Models.Funcionario", b =>
                {
                    b.Property<int>("FuncionarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FuncionarioId");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("SafetyTourism.Models.Recomendacao", b =>
                {
                    b.Property<int>("RecomendacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Conteudo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecomendacaoId");

                    b.ToTable("Recomendacao");
                });

            modelBuilder.Entity("SafetyTourism.Models.Utilizador", b =>
                {
                    b.Property<int>("UtilizadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Morada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tel")
                        .HasColumnType("int");

                    b.HasKey("UtilizadorId");

                    b.ToTable("Utilizador");
                });

            modelBuilder.Entity("SafetyTourism.Models.AfectadoPor", b =>
                {
                    b.HasOne("SafetyTourism.Models.Destino", "Destino")
                        .WithMany("Afectados")
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafetyTourism.Models.Doenca", "Doenca")
                        .WithMany()
                        .HasForeignKey("DoencaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destino");

                    b.Navigation("Doenca");
                });

            modelBuilder.Entity("SafetyTourism.Models.Doenca", b =>
                {
                    b.HasOne("SafetyTourism.Models.Recomendacao", "Recomendacao")
                        .WithMany()
                        .HasForeignKey("RecomendacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recomendacao");
                });

            modelBuilder.Entity("SafetyTourism.Models.Destino", b =>
                {
                    b.Navigation("Afectados");
                });
#pragma warning restore 612, 618
        }
    }
}
